version: '3.8'
services:
  app:
    container_name: teleport-challenge-petite
    build: .
    volumes:
      - /app/node_modules
      - ./:/app
    command: yarn start:server
    ports:
      - "8080:8080"